site_name: TeleHealthCareAI
site_url: https://telehealthcareai.org

docs_dir: pages
site_dir: build

extra:
  enumerate: !!python/name:builtins.enumerate

theme:
  name: null
  custom_dir: "theme/"
  features:
    - content.code.copy
  palette:
    primary: indigo

extra_css:
  - css/style.css

extra_javascript:
  - js/script.js
  - plugins/bootstrap/bootstrap.min.js
  - plugins/google-map/gmap.js
  - plugins/jquery/jquery.js

nav:
  - About: "about/index.md"

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - include-markdown:
      start: <!-- start -->
      end: <!-- end -->

  - rss:
      abstract_chars_count: 160 # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
        default_time: "09:30"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
